### ISSUE TITLE
How to put PVA in an epicscorelibs provided IOC?

### ISSUE THREAD

**Issue by thomascobb** [mdavidsaver/epicscorelibs#13]
I'm trying to put PVA support in pythonIoc, but not quite sure how to go about it. I took a punt at:
```python
# setup.py
ext = Extension(
    dsos = ['epicscorelibs.lib.qsrv', 'epicscorelibs.lib.dbCore', 'epicscorelibs.lib.Com'],
    ...
)
# __init__.py
iocshRegisterCommon()
dbLoadDatabase("base.dbd", os.path.join(path.base_path, "dbd"), None)
dbLoadDatabase("qsrv.dbd", os.path.join(path.base_path, "dbd"), None)
dbLoadDatabase("devIocStats.dbd", os.path.dirname(__file__), None)

if registerRecordDeviceDriver(pdbbase):
    raise RuntimeError('Error registering')
```
and got
```
Unable to find symbol 'pvar_func_register_func_QSRV_image_demo' : /scratch/tmc43/pipenv/pythonIoc-y_I5oBLg/lib/python3.7/site-packages/epicscorelibs/lib/libdbCore.so.7.0.4.99.1: undefined symbol: pvar_func_register_func_QSRV_image_demo
Unable to find function 'QSRV_image_demo' : (null)
Traceback (most recent call last):
  File "docs/examples/example_asyncio_ioc.py", line 2, in <module>
    from softioc import softioc, builder, asyncio_dispatcher
  File "/dls/science/users/tmc43/common/python/pythonIoc/softioc/__init__.py", line 20, in <module>
    raise RuntimeError('Error registering')
RuntimeError: Error registering
```
Any ideas?

**Comment by mdavidsaver** [comment]
Firstly, in addition to `qsrv.dbd`, you also want to load `PVAServerRegister.dbd`.  The later is what actually causes a PVA server to start.

The missing symbols should be provided by `libqsrv.so`.  That they are reported missing my be a symptom of an incomplete dependency list.  Can you try replacing

> ```python
>     dsos = ['epicscorelibs.lib.qsrv', 'epicscorelibs.lib.dbCore', 'epicscorelibs.lib.Com'],
> ```

with the complete dependency list:

```py
dsos = [
    'epicscorelibs.lib.qsrv',
    'epicscorelibs.lib.pvAccessIOC,
    'epicscorelibs.lib.pvAccess
    'epicscorelibs.lib.pvData,
    'epicscorelibs.lib.dbRecStd',
    'epicscorelibs.lib.dbCore',
    'epicscorelibs.lib.ca',
    'epicscorelibs.lib.Com',
],
```

cf. `pdbApp/Makefile` in the pva2pva repository.

```makefile
softIocPVA_DBD += softIoc.dbd
softIocPVA_DBD += PVAServerRegister.dbd
softIocPVA_DBD += qsrv.dbd
...
softIocPVA_LIBS += qsrv
softIocPVA_LIBS += $(EPICS_BASE_PVA_CORE_LIBS)
# expand as "pvAccessIOC pvAccessCA pvAccess pvData"
softIocPVA_LIBS += $(EPICS_BASE_IOC_LIBS)
# expands as "dbRecStd dbCore ca Com"
```

```sh
$ make -s -C pdbApp/O.linux-x86_64 PRINT.softIocPVA_LIBS
softIocPVA_LIBS = qsrv pvAccessIOC pvAccessCA pvAccess pvData dbRecStd dbCore ca Com
```

`pvAccessCA` is not actually used by QSRV, although loading it shouldn't have ill effects.

**Comment by thomascobb** [comment]
I still get the same error with those changes.
Here's the CI build: https://github.com/dls-controls/pythonIoc/actions/runs/1001686870
I tried with `epicscorelibs==7.0.5.99.1.0a2` and the same result

`pvar_func_register_func_QSRV_image_demo` doesn't seem to be defined in any of the so files, should it be? Other symbols I expect to be there are present:
```
$ grep pvar_func_register_func_QSRV_image_demo /scratch/tmc43/pipenv/pythonIoc-y_I5oBLg/lib/python3.7/site-packages/epicscorelibs/lib/*.so
$ grep registerRecordDeviceDriver /scratch/tmc43/pipenv/pythonIoc-y_I5oBLg/lib/python3.7/site-packages/epicscorelibs/lib/*.so
Binary file /scratch/tmc43/pipenv/pythonIoc-y_I5oBLg/lib/python3.7/site-packages/epicscorelibs/lib/libdbCore.so matches
```

**Comment by mdavidsaver** [comment]
Ok, so the epicscorelibs build must be incomplete.

fyi. I will likely be publishing a 7.0.6 alpha build today.

**Comment by thomascobb** [comment]
Ok, will wait for that.

BTW, `pvar_func_register_func_QSRV_image_demo` seems an odd name, any idea what it actually does?

**Comment by mdavidsaver** [comment]
Well, yes.  It is my doing :)  This symbol lookup results from the line `function(QSRV_image_demo)` in `qsrv.dbd`.

Rightly or wrongly, `libqsrv.so` includes the device supports used by the QSRV demo IOCs.

**Comment by mdavidsaver** [comment]
I've uploaded [7.0.6.99.1.0a1](https://pypi.org/project/epicscorelibs/7.0.6.99.1.0a1/), which should fix this.

**Comment by thomascobb** [comment]
Thanks, build error is gone and I can run a pythonIoc with PVA!

Please can you let me know when you've released a non-alpha version and released p4p against it, and I'll add some tests and make a release of pythonIoc against it...

**Comment by mdavidsaver** [comment]
I've uploaded epicscorelibs [7.0.6.99.1.0](https://pypi.org/project/epicscorelibs/7.0.6.99.1.0/) and P4P [3.5.4](https://pypi.org/project/p4p/3.5.4/).

**Comment by thomascobb** [comment]
Perfect, it's working now!
