### ISSUE TITLE
Compile epicecorelibs with -j1

### ISSUE THREAD

**Issue by klenze** [mdavidsaver/epicscorelibs#18]
I tried to install epicscorelibs on a raspi3 (1GiB) with pip3, but the setup system insists on using four processes in parallel, which will then slow down to a crawl when four g++ instances manage to eat all available memory.

Is there a good way to tell pip/setuptools to only use a single thread, like make -j1 would?

I tried pip with ``--install-option="--jobs=1"`` but then it does not compile at all.

MAKEOPTS does not do anything because it appears that make is not used as a build system by pip. 

I also tried cloning epicscorelibs and compiling it manually, e.g. 
```
  python3 setup.py build_ext -j1
```
but it seems that all options for build_ext are ignored (e.g. ``-c /bin/false``) despite appearing in ``./setup.py --help build_ext``. 

From my understanding, installing EPICS and then having epicscorelibs detect and use the installation is also not an option. 

I guess I could boot my raspi with the nosmp boot option and hope that setuptools_dso instantiates one job per CPU, but I feel that there should be a more elegant option to set this. 

Cheers,
   Philipp

**Comment by mdavidsaver** [comment]
[setuptools_dso](https://mdavidsaver.github.io/setuptools_dso/) has a special environment variable [`$NUM_JOBS`](https://github.com/mdavidsaver/setuptools_dso/blob/0b7223087d0d25b43fc31f095d0987513002a5e3/src/setuptools_dso/dsocmd.py#L352).  Set `NUM_JOBS=1` for sequential compilation.

**Comment by klenze** [comment]
I think the Pi is running on a generic debian.

```NUM_JOBS=1 pip3 install epicscorelibs```

worked fine!

Thanks for the help,
   Philipp
