### ISSUE TITLE
[macos] epicsMutexOsdUnlock but caller is not owner thrown when using p4p together with pyepics

### ISSUE THREAD

**Issue by juanfem** [mdavidsaver/epicscorelibs#9]
On my mac, when I import both p4p and pyepics and then try to use pyepics, it crashes and the following message is thrown:
```
epicsMutexOsdUnlock but caller is not owner
epicsMutexOsdUnlock but caller is not ownerThread _main_ (0x7fdfd4d04540) can't proceed, suspending.
Dumping a stack trace of thread '_main_':
```

A small script that can reproduce this issue is here:
```
from p4p.client.thread import Context
from epics import PV

pv = PV('TEST')

print(pv.get())
```
The `TEST` PV does not need to exist.

This seems to be a regression, either here or on p4p, since it used to work on my mac using v7.0.3.99.4.0 (and p4p-3.5.2). I downgraded to that version and it works. I cannot be sure that the issue is in this library and not on p4p, since p4p 3.5.3 requires the latest version of epicscorelibs. However, this [commit](https://github.com/mdavidsaver/epicscorelibs/commit/5a8b6e4111b869e8913b7bfaff4c56b546fb8879 ) suggests me it is here.

I have only tested 7.0.4.99.1.2, but I assume that the previous 2 versions also carry this issue, since the commit previously mentioned was first included in 7.0.4.99.1.0.

I cannot reproduce this issue on Linux and I didn't try on Windows. Given that this seems to be related to POSIX systems, I guess it shouldn't affect the Windows version.

**Comment by mdavidsaver** [comment]
Please try adding the following line before importing pyepics.

```py
import epicscorelibs.path.pyepics  # <<< add
from p4p.client.thread import Context
from epics import PV
```

This should avoid loading two different versions of `libca` into the same process.

**Comment by juanfem** [comment]
Yes, that works. Thanks for the fast reply.

I've just realised I had a similar issue in the past, but that time it was because I was setting the PYEPICS_LIBCA variable.

**Comment by mdavidsaver** [comment]
`epicscorelibs.path.pyepics` is only automating this.

https://github.com/mdavidsaver/epicscorelibs/blob/947818ddfea68084e269cd1934841cdbc10e5ed2/src/python/epicscorelibs/path/pyepics.py#L21-L22
